<?php
/**
 * ChargeDateTimeType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * elepay API リファレンス
 *
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 0.0.2
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\jp.elestyle.elepay.model;
use \Swagger\Client\ObjectSerializer;

/**
 * ChargeDateTimeType Class Doc Comment
 *
 * @category Class
 * @description 時間項目 - expiry_time 支払有効時間 - paid_time 払う時間 - settle_time 支払締め時間 - create_time 支払新規時間 - update_time 支払更新時間
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ChargeDateTimeType
{
    /**
     * Possible values of this enum
     */
    const EXPIRY_TIME = 'expiry_time';
    const PAID_TIME = 'paid_time';
    const SETTLE_TIME = 'settle_time';
    const CREATE_TIME = 'create_time';
    const UPDATE_TIME = 'update_time';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EXPIRY_TIME,
            self::PAID_TIME,
            self::SETTLE_TIME,
            self::CREATE_TIME,
            self::UPDATE_TIME,
        ];
    }
}


