<?php
/**
 * ElepayError
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * elepay API リファレンス
 *
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 0.0.2
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\jp.elestyle.elepay.model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ElepayError Class Doc Comment
 *
 * @category Class
 * @description エラー情報
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ElepayError implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ElepayError';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'type' => 'string',
        'code' => 'string',
        'message' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'type' => null,
        'code' => null,
        'message' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'code' => 'code',
        'message' => 'message'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'code' => 'setCode',
        'message' => 'setMessage'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'code' => 'getCode',
        'message' => 'getMessage'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const TYPE_NOT_FOUND = 'not_found';
    const TYPE_INVALID_REQUEST_ERROR = 'invalid_request_error';
    const TYPE_CHANNEL_VALIDATION_ERROR = 'channel_validation_error';
    const TYPE_CHANNEL_ERROR = 'channel_error';
    const TYPE_PROVIDER_ERROR = 'provider_error';
    const TYPE_CONNECTION_ERROR = 'connection_error';
    const TYPE_PROCESS_ERROR = 'process_error';
    const TYPE_AUTHENTICATION_ERROR = 'authentication_error';
    const TYPE_FORBIDDEN_ERROR = 'forbidden_error';
    const TYPE_RATE_LIMIT_ERROR = 'rate_limit_error';
    const TYPE_API_ERROR = 'api_error';
    const TYPE_API_CONNECTION_ERROR = 'api_connection_error';
    const CODE_NOT_FOUND = 'not_found';
    const CODE_NOT_FOUND_CHARGE = 'not_found_charge';
    const CODE_AUTH_INVALID_CREDENTIAL = 'auth_invalid_credential';
    const CODE_AUTH_INVALID_PROVIDER = 'auth_invalid_provider';
    const CODE_INVALID_REQUEST = 'invalid_request';
    const CODE_INVALID_ORDER_NO = 'invalid_order_no';
    const CODE_INVALID_PAYMENT_METHOD = 'invalid_payment_method';
    const CODE_INVALID_AMOUNT = 'invalid_amount';
    const CODE_INVALID_TOKEN = 'invalid_token';
    const CODE_INVALID_FRONT_URL = 'invalid_front_url';
    const CODE_INVALID_CANCEL_URL = 'invalid_cancel_url';
    const CODE_INVALID_CONTRACT_NUMBER = 'invalid_contract_number';
    const CODE_INVALID_USERNAME = 'invalid_username';
    const CODE_INVALID_EMAIL = 'invalid_email';
    const CODE_INVALID_PASSWORD = 'invalid_password';
    const CODE_INVALID_ORDER_NO_LENGTH = 'invalid_order_no_length';
    const CODE_INVALID_STATUS_CHANGE = 'invalid_status_change';
    const CODE_INVALID_STATUS_CHANGE_BY_APP = 'invalid_status_change_by_app';
    const CODE_INVALID_STATUS_CHANGE_BY_PROVIDER = 'invalid_status_change_by_provider';
    const CODE_INVALID_PROVIDER_UNIQUE_ID = 'invalid_provider_unique_id';
    const CODE_INVALID_PROVIDER_CAPTURE_ID = 'invalid_provider_capture_id';
    const CODE_INVALID_BUYER_NAME = 'invalid_buyer_name';
    const CODE_INVALID_BUYER_PHONE = 'invalid_buyer_phone';
    const CODE_INVALID_BUYER_EMAIL = 'invalid_buyer_email';
    const CODE_INVALID_BUYER_ZIP = 'invalid_buyer_zip';
    const CODE_INVALID_BUYER_ADDRESS1 = 'invalid_buyer_address1';
    const CODE_INVALID_BUYER_ADDRESS2 = 'invalid_buyer_address2';
    const CODE_INVALID_CODE_URL = 'invalid_code_url';
    const CODE_INVALID_SHOP_ID = 'invalid_shop_id';
    const CODE_INVALID_SHOP_NAME = 'invalid_shop_name';
    const CODE_INVALID_SHOP_NO = 'invalid_shop_no';
    const CODE_INVALID_PRODUCT_ID = 'invalid_product_id';
    const CODE_INVALID_PRODUCT_NAME = 'invalid_product_name';
    const CODE_INVALID_PRODUCT_PRICE = 'invalid_product_price';
    const CODE_INVALID_PRODUCT_COUNT = 'invalid_product_count';
    const CODE_INVALID_SETTING_TYPE = 'invalid_setting_type';
    const CODE_INVALID_SETTING_NAME = 'invalid_setting_name';
    const CODE_INVALID_CATEGORY_ID = 'invalid_category_id';
    const CODE_INVALID_CATEGORY_NAME = 'invalid_category_name';
    const CODE_INVALID_THEME_NAME = 'invalid_theme_name';
    const CODE_INVALID_LABEL_NAME = 'invalid_label_name';
    const CODE_INVALID_SKU = 'invalid_sku';
    const CODE_INVALID_CHARGE = 'invalid_charge';
    const CODE_INVALID_FROM = 'invalid_from';
    const CODE_INVALID_TO = 'invalid_to';
    const CODE_INVALID_EXPORT_DATA_DATE_RANGE = 'invalid_export_data_date_range';
    const CODE_INCORRECT_CURRENCY = 'incorrect_currency';
    const CODE_INCORRECT_CARD_NUMBER = 'incorrect_card_number';
    const CODE_INCORRECT_AMOUNT = 'incorrect_amount';
    const CODE_INCORRECT_MERCHANT_ID = 'incorrect_merchant_id';
    const CODE_INCORRECT_PRODUCT_ID = 'incorrect_product_id';
    const CODE_INCORRECT_EXPORT_DATA_DATE_RANGE = 'incorrect_export_data_date_range';
    const CODE_INCORRECT_STATUS = 'incorrect_status';
    const CODE_PROVIDER_RESPONSE_RESULT_FAILED = 'provider_response_result_failed';
    const CODE_NO_SUCH_TOKEN = 'no_such_token';
    const CODE_DUPLICATE_ORDER_NO = 'duplicate_order_no';
    const CODE_DUPLICATE_CONTRACT_NUMBER = 'duplicate_contract_number';
    const CODE_DUPLICATE_EMAIL = 'duplicate_email';
    const CODE_DUPLICATE_LEGAL_REGISTRATION_NO = 'duplicate_legal_registration_no';
    const CODE_DUPLICATE_KEY = 'duplicate_key';
    const CODE_EXPIRED_CARD = 'expired_card';
    const CODE_CARD_DECLINED = 'card_declined';
    const CODE_PROCESSING_CARD_ERROR = 'processing_card_error';
    const CODE_REQUIRED_KEY = 'required_key';
    const CODE_CHARGE_ALREADY_CAPTURED = 'charge_already_captured';
    const CODE_CHARGE_ALREADY_REFUNDED = 'charge_already_refunded';
    const CODE_REFUSED_REFUND = 'refused_refund';
    const CODE_REFUSED_REFUND_NON_CAPTURED = 'refused_refund_non_captured';
    const CODE_INACTIVE_APPLICATION = 'inactive_application';
    const CODE_INACTIVE_PAYMENT_METHOD = 'inactive_payment_method';
    const CODE_INACTIVE_PRODUCT = 'inactive_product';
    const CODE_EXIST_PAYMENT_METHOD = 'exist_payment_method';
    const CODE_PROCESS_ERROR = 'process_error';
    const CODE_API_CONNECTION_ERROR = 'api_connection_error';
    const CODE_API_ERROR = 'api_error';
    const CODE_FORBIDDEN = 'forbidden';
    const CODE_RECAPTCHA_FAIL = 'recaptcha_fail';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_NOT_FOUND,
            self::TYPE_INVALID_REQUEST_ERROR,
            self::TYPE_CHANNEL_VALIDATION_ERROR,
            self::TYPE_CHANNEL_ERROR,
            self::TYPE_PROVIDER_ERROR,
            self::TYPE_CONNECTION_ERROR,
            self::TYPE_PROCESS_ERROR,
            self::TYPE_AUTHENTICATION_ERROR,
            self::TYPE_FORBIDDEN_ERROR,
            self::TYPE_RATE_LIMIT_ERROR,
            self::TYPE_API_ERROR,
            self::TYPE_API_CONNECTION_ERROR,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCodeAllowableValues()
    {
        return [
            self::CODE_NOT_FOUND,
            self::CODE_NOT_FOUND_CHARGE,
            self::CODE_AUTH_INVALID_CREDENTIAL,
            self::CODE_AUTH_INVALID_PROVIDER,
            self::CODE_INVALID_REQUEST,
            self::CODE_INVALID_ORDER_NO,
            self::CODE_INVALID_PAYMENT_METHOD,
            self::CODE_INVALID_AMOUNT,
            self::CODE_INVALID_TOKEN,
            self::CODE_INVALID_FRONT_URL,
            self::CODE_INVALID_CANCEL_URL,
            self::CODE_INVALID_CONTRACT_NUMBER,
            self::CODE_INVALID_USERNAME,
            self::CODE_INVALID_EMAIL,
            self::CODE_INVALID_PASSWORD,
            self::CODE_INVALID_ORDER_NO_LENGTH,
            self::CODE_INVALID_STATUS_CHANGE,
            self::CODE_INVALID_STATUS_CHANGE_BY_APP,
            self::CODE_INVALID_STATUS_CHANGE_BY_PROVIDER,
            self::CODE_INVALID_PROVIDER_UNIQUE_ID,
            self::CODE_INVALID_PROVIDER_CAPTURE_ID,
            self::CODE_INVALID_BUYER_NAME,
            self::CODE_INVALID_BUYER_PHONE,
            self::CODE_INVALID_BUYER_EMAIL,
            self::CODE_INVALID_BUYER_ZIP,
            self::CODE_INVALID_BUYER_ADDRESS1,
            self::CODE_INVALID_BUYER_ADDRESS2,
            self::CODE_INVALID_CODE_URL,
            self::CODE_INVALID_SHOP_ID,
            self::CODE_INVALID_SHOP_NAME,
            self::CODE_INVALID_SHOP_NO,
            self::CODE_INVALID_PRODUCT_ID,
            self::CODE_INVALID_PRODUCT_NAME,
            self::CODE_INVALID_PRODUCT_PRICE,
            self::CODE_INVALID_PRODUCT_COUNT,
            self::CODE_INVALID_SETTING_TYPE,
            self::CODE_INVALID_SETTING_NAME,
            self::CODE_INVALID_CATEGORY_ID,
            self::CODE_INVALID_CATEGORY_NAME,
            self::CODE_INVALID_THEME_NAME,
            self::CODE_INVALID_LABEL_NAME,
            self::CODE_INVALID_SKU,
            self::CODE_INVALID_CHARGE,
            self::CODE_INVALID_FROM,
            self::CODE_INVALID_TO,
            self::CODE_INVALID_EXPORT_DATA_DATE_RANGE,
            self::CODE_INCORRECT_CURRENCY,
            self::CODE_INCORRECT_CARD_NUMBER,
            self::CODE_INCORRECT_AMOUNT,
            self::CODE_INCORRECT_MERCHANT_ID,
            self::CODE_INCORRECT_PRODUCT_ID,
            self::CODE_INCORRECT_EXPORT_DATA_DATE_RANGE,
            self::CODE_INCORRECT_STATUS,
            self::CODE_PROVIDER_RESPONSE_RESULT_FAILED,
            self::CODE_NO_SUCH_TOKEN,
            self::CODE_DUPLICATE_ORDER_NO,
            self::CODE_DUPLICATE_CONTRACT_NUMBER,
            self::CODE_DUPLICATE_EMAIL,
            self::CODE_DUPLICATE_LEGAL_REGISTRATION_NO,
            self::CODE_DUPLICATE_KEY,
            self::CODE_EXPIRED_CARD,
            self::CODE_CARD_DECLINED,
            self::CODE_PROCESSING_CARD_ERROR,
            self::CODE_REQUIRED_KEY,
            self::CODE_CHARGE_ALREADY_CAPTURED,
            self::CODE_CHARGE_ALREADY_REFUNDED,
            self::CODE_REFUSED_REFUND,
            self::CODE_REFUSED_REFUND_NON_CAPTURED,
            self::CODE_INACTIVE_APPLICATION,
            self::CODE_INACTIVE_PAYMENT_METHOD,
            self::CODE_INACTIVE_PRODUCT,
            self::CODE_EXIST_PAYMENT_METHOD,
            self::CODE_PROCESS_ERROR,
            self::CODE_API_CONNECTION_ERROR,
            self::CODE_API_ERROR,
            self::CODE_FORBIDDEN,
            self::CODE_RECAPTCHA_FAIL,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['code'] = isset($data['code']) ? $data['code'] : null;
        $this->container['message'] = isset($data['message']) ? $data['message'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getCodeAllowableValues();
        if (!is_null($this->container['code']) && !in_array($this->container['code'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'code', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type エラーコードとメッセージ
     *
     * @return $this
     */
    public function setType($type)
    {
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($type) && !in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string $code エラーコード
     *
     * @return $this
     */
    public function setCode($code)
    {
        $allowedValues = $this->getCodeAllowableValues();
        if (!is_null($code) && !in_array($code, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'code', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string $message エラーメッセージ
     *
     * @return $this
     */
    public function setMessage($message)
    {
        $this->container['message'] = $message;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


