<?php
/**
 * PaymentMethodType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * elepay API リファレンス
 *
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 0.0.2
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\jp.elestyle.elepay.model;
use \Swagger\Client\ObjectSerializer;

/**
 * PaymentMethodType Class Doc Comment
 *
 * @category Class
 * @description 支払い方法 - alipay - alipay_web - applepay - applepay_cn - applepay_cn_web - creditcard - googlepay - paypal - unionpay - unionpay_web - linepay - linepay_web - wechat - wechat_qr - paidy - paypay
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PaymentMethodType
{
    /**
     * Possible values of this enum
     */
    const ALIPAY = 'alipay';
    const ALIPAY_WEB = 'alipay_web';
    const APPLEPAY = 'applepay';
    const APPLEPAY_WEB = 'applepay_web';
    const APPLEPAY_CN = 'applepay_cn';
    const APPLEPAY_CN_WEB = 'applepay_cn_web';
    const CREDITCARD = 'creditcard';
    const GOOGLEPAY = 'googlepay';
    const PAYPAL = 'paypal';
    const UNIONPAY = 'unionpay';
    const UNIONPAY_WEB = 'unionpay_web';
    const LINEPAY_WEB = 'linepay_web';
    const LINEPAY = 'linepay';
    const WECHAT = 'wechat';
    const WECHAT_QR = 'wechat_qr';
    const PAIDY = 'paidy';
    const PAYPAY = 'paypay';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ALIPAY,
            self::ALIPAY_WEB,
            self::APPLEPAY,
            self::APPLEPAY_WEB,
            self::APPLEPAY_CN,
            self::APPLEPAY_CN_WEB,
            self::CREDITCARD,
            self::GOOGLEPAY,
            self::PAYPAL,
            self::UNIONPAY,
            self::UNIONPAY_WEB,
            self::LINEPAY_WEB,
            self::LINEPAY,
            self::WECHAT,
            self::WECHAT_QR,
            self::PAIDY,
            self::PAYPAY,
        ];
    }
}


